'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { supabase } from '../../../../../lib/supabaseClient';

function d(v){return v?new Date(v).toLocaleString('fr-FR'): '—';}
export default function HistoriqueConducteur({params}){
 const {id}=params; const router=useRouter(); const [ok,setOk]=useState(null); const [loading,setLoading]=useState(true); const [data,setData]=useState(null); const [err,setErr]=useState('');
 useEffect(()=>{(async()=>{const {data:s}=await supabase.auth.getSession();if(!s.session)return router.push('/agent/login');const {data:a}=await supabase.from('agents').select('role,actif').eq('user_id',s.session.user.id).maybeSingle();if(!a?.actif||!['agent','responsable','responsable_regional','admin'].includes(a.role))return router.push('/agent/login');setOk(true);
 const {data:c}=await supabase.from('conducteurs').select('id,nom,prenom,numero_cni,telephone,statut').eq('id',id).maybeSingle();if(!c){setErr('Conducteur introuvable.');setLoading(false);return;}
 const [{data:permis},{data:liens}]=await Promise.all([supabase.from('permis_conduire').select('id,numero_permis,statut,date_expiration,categories').eq('conducteur_id',id).order('created_at',{ascending:false}),supabase.from('conducteur_engins').select('engin_id,est_principal,date_debut,date_fin').eq('conducteur_id',id).order('created_at',{ascending:false})]);
 const enginIds=(liens||[]).map(x=>x.engin_id); let engins=[]; if(enginIds.length){const r=await supabase.from('engins').select('id,plaque,marque,modele,statut').in('id',enginIds);engins=r.data||[];}
 const [{data:pv},{data:accPers}]=await Promise.all([supabase.from('infractions').select('id,numero_pv,date_heure,lieu,type_infraction,montant,statut,points_retires,engin_id').eq('conducteur_id',id).order('date_heure',{ascending:false}).limit(200),supabase.from('accident_personnes').select('accident_id,type_personne,nom,blessure,evacuee').eq('nom',c.nom).limit(100)]);
 const accIds=(accPers||[]).map(x=>x.accident_id); let accidents=[]; if(accIds.length){const r=await supabase.from('accidents').select('id,numero_dossier,date_heure,lieu,type_accident,gravite,statut_enquete').in('id',accIds).order('date_heure',{ascending:false});accidents=r.data||[];}
 setData({c,permis:permis||[],liens:liens||[],engins,pv:pv||[],accidents});setLoading(false);})();},[id]);
 if(ok===null||loading)return <div className="shell"><div className="content"><p>Chargement…</p></div></div>;
 if(err)return <div className="shell"><div className="content"><p>{err}</p></div></div>;
 return <div className="shell" style={{maxWidth:900}}><div className="header"><button onClick={()=>router.back()} className="btn secondaire" style={{width:'auto',marginBottom:12}}>← Retour</button><p className="sigle">Registre national</p><h1>Historique — {data.c.nom} {data.c.prenom||''}</h1><p style={{color:'var(--ink-soft)'}}>Vue chronologique des événements rattachés au dossier conducteur.</p></div><div className="content">
 <section><h2>Résumé</h2><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10}}><div className="liste-item">Permis : <strong>{data.permis.length}</strong></div><div className="liste-item">Engins associés : <strong>{data.engins.length}</strong></div><div className="liste-item">PV : <strong>{data.pv.length}</strong></div><div className="liste-item">Accidents retrouvés : <strong>{data.accidents.length}</strong></div></div></section><div className="divider"/>
 <section><h2>Permis</h2>{data.permis.length?data.permis.map(p=><div className="liste-item" key={p.id}><strong>{p.numero_permis}</strong> · {p.statut} · expiration {p.date_expiration||'—'}<div className="meta">Catégories : {(p.categories||[]).join(', ')||'—'}</div></div>):<p>Aucun permis.</p>}</section><div className="divider"/>
 <section><h2>Engins associés</h2>{data.engins.length?data.engins.map(e=><Link key={e.id} href={'/agent/fiche/'+e.id} className="liste-item" style={{display:'block'}}><strong>{e.plaque||'Sans plaque'}</strong> · {e.marque||''} {e.modele||''}<div className="meta">Statut : {e.statut||'—'}</div></Link>):<p>Aucun engin associé.</p>}</section><div className="divider"/>
 <section><h2>Procès-verbaux ({data.pv.length})</h2>{data.pv.length?data.pv.map(x=><div className="liste-item" key={x.id}><strong>{x.numero_pv}</strong> · {x.type_infraction}<div className="meta">{d(x.date_heure)} · {x.lieu||'Lieu non renseigné'} · statut {x.statut}</div><div className="meta">Montant : {x.montant??'—'} · points : {x.points_retires||0}</div></div>):<p>Aucun PV.</p>}</section><div className="divider"/>
 <section><h2>Accidents retrouvés</h2><p style={{color:'var(--ink-soft)',fontSize:13}}>Cette correspondance repose sur le nom enregistré dans les personnes impliquées ; elle doit être confirmée par l’agent.</p>{data.accidents.length?data.accidents.map(x=><Link key={x.id} href={'/agent/accidents/'+x.id} className="liste-item" style={{display:'block'}}><strong>{x.numero_dossier||x.id.slice(0,8)}</strong> · {x.type_accident} · {x.gravite}<div className="meta">{d(x.date_heure)} · {x.lieu} · enquête : {x.statut_enquete}</div></Link>):<p>Aucun accident retrouvé.</p>}</section>
 </div></div>;
}